<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="windows-clone" name="com.DWP.安全管理.用户管理.script.User" tests="4" failures="0" timestamp="23 Jul 2018 07:30:51 GMT" time="0.000" errors="4">
  <testcase name="del" time="0.000" classname="com.DWP.安全管理.用户管理.script.User">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\del.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\del.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\del.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.安全管理.用户管理.script.User.deldata(User.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- del -->
  <testcase name="add" time="0.000" classname="com.DWP.安全管理.用户管理.script.User">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\add.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\add.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\add.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.安全管理.用户管理.script.User.adddata(User.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- add -->
  <testcase name="update" time="0.000" classname="com.DWP.安全管理.用户管理.script.User">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\update.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\update.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\update.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.安全管理.用户管理.script.User.updatedata(User.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- update -->
  <testcase name="query" time="0.000" classname="com.DWP.安全管理.用户管理.script.User">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\query.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\query.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\安全管理\用户管理\data\query.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.安全管理.用户管理.script.User.querydata(User.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- query -->
</testsuite> <!-- com.DWP.安全管理.用户管理.script.User -->
